/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */



#include"stdlib.h"
#include "lcd.h"
#include "keypad.h"
#include "STM32_GPIO_DRIVER.h"
#include "STM32_momery map.h"

#define ZERO 0x01
#define ONE 0x79
#define TWO 0x24
#define THREE 0x30
#define FOUR 0x4C
#define FIVE 0x12
#define SIX 0x02
#define SEVEN 0x19
#define EIGHT 0x00
#define NINE 0x10

void clock_init() {
	//Enable clock GPIOA
	RCC_ENABLE_GPIOA();
	//Enable clock GPIOB Bit 3 IOPBEN: IO port B clock enable
	RCC_ENABLE_GPIOB();
}
void GPIO_init() {

	Gpio_pinconfig PinCfg;

	//PA1 input HighZ Floating input (reset state)
//	PinCfg.gpio_pin10 = GPIO_PIN_1;
//	PinCfg.gpiox_mode = gpiox_mode_INPUT_FLO;
//	MCAL_GPIO_Init(GPIOA, &PinCfg);

//PB1 (output PUSH pull Mode)
//01: Output mode, max speed 10 MHz.
//CNF 00: General purpose output push-pull
	PinCfg.gpiox_pinnuber = gpio_pin9;
	PinCfg.gpiox_mode = GPIO_MODE_OUTPUT_PP;
	PinCfg.gpiox_outspeed= GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

	PinCfg.gpiox_pinnuber = gpio_pin10;
	PinCfg.gpiox_mode = GPIO_MODE_OUTPUT_PP;
	PinCfg.gpiox_outspeed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

	PinCfg.gpiox_pinnuber = gpio_pin11;
	PinCfg.gpiox_mode = GPIO_MODE_OUTPUT_PP;
	PinCfg.gpiox_outspeed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

	PinCfg.gpiox_pinnuber = gpio_pin12;
	PinCfg.gpiox_mode = GPIO_MODE_OUTPUT_PP;
	PinCfg.gpiox_outspeed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

	PinCfg.gpiox_pinnuber = gpio_pin13;
	PinCfg.gpiox_mode = GPIO_MODE_OUTPUT_PP;
	PinCfg.gpiox_outspeed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

	//============================

	//PA13 input HighZ Floating input (reset state)
	PinCfg.gpiox_pinnuber = gpio_pin14;
	PinCfg.gpiox_mode = GPIO_MODE_OUTPUT_PP;
	PinCfg.gpiox_outspeed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

	//PB13 (output PUSH pull Mode)
	PinCfg.gpiox_pinnuber = gpio_pin15;
	PinCfg.gpiox_mode = GPIO_MODE_OUTPUT_PP;
	PinCfg.gpiox_outspeed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

}
void wait_ms(uint32_t time) {
	uint32_t i, j;
	for (i = 0; i < time; i++)
		for (j = 0; j < 255; j++)
			;
}
int main(void) {

	clock_init();
	LCD_INIT();
	unsigned char key_pressed;
	LCD_WRITE_STRING("HEY");
	wait_ms(30);
	LCD_clear_screen();
	GPIO_init();
	unsigned char LCD_DISPLAY [11] = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0'};
	unsigned char DISPLAY [11] = {ZERO, ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, ZERO};
	for (unsigned char i = 0; i < 11; i++) {
		LCD_WRITE_CHAR(LCD_DISPLAY[i]);
		MCAL_GPIO_WritePort(GPIOB, DISPLAY[i] << 9); /* write data on to the LED port */
		wait_ms(100);
		/* wait for 1 second */
	}
//	MCAL_GPIO_WritePort(GPIOB, 0xDE);
//	wait_ms(100);
	LCD_clear_screen();
	Keypad_init();
	LCD_WRITE_STRING("Keypad is ready");
	wait_ms(30);
	LCD_clear_screen();

	while (1) {

		key_pressed = Keypad_getkey();
		switch (key_pressed) {
		case 'A':
			break;
		case '?':
			LCD_clear_screen();
			break;
		default:
			LCD_WRITE_CHAR(key_pressed);
			break;
		}
//		//PA1 >>>Connected external PUR
//
//		if ( MCAL_GPIO_ReadPin(GPIOA, gpio_pin1) == 0) // press
//		{
//			MCAL_GPIO_TogglePin(GPIOB, gpio_pin1);
//			while  (MCAL_GPIO_ReadPin(GPIOA, gpio_pin1) == 0)  ; //Single Pressing
//		}
//		//PA13 >>>Connected external PDR
//		if ( MCAL_GPIO_ReadPin(GPIOA, gpio_pin13) == 1) //Multi Pressing
//		{
//			MCAL_GPIO_TogglePin(GPIOB, gpio_pin13);
//		}
//		LCD_WRITE_STRING("HEY");
//		wait_ms(30);
//		LCD_clear_screen();
	}
}
